[package]
name = "luminol"
version = "0.4.0"
authors = [
    "Lily Lyons <lily@nowaffles.com>",
    "Egor Poleshko <somedevfox@gmail.com>",
]
edition = "2021"
rust-version = "1.62"
description = "Luminol is a FOSS recreation of RPG Maker XP in Rust with love ❤️"
license = "GPL-3.0"
readme = "README.md"
repository = "https://github.com/Speak2Erase/Luminol"
keywords = ["gamedev", "rpg", "rpg-maker"]
categories = ["games"]
build = "build.rs"

default-run = "luminol"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe.workspace = true
egui.workspace = true
egui_extras.workspace = true
epaint.workspace = true

rfd.workspace = true

parking_lot.workspace = true
once_cell.workspace = true

image.workspace = true

steamworks = { version = "0.10.0", optional = true }
crc = { version = "3.0.1", optional = true }

tracing-subscriber = "0.3.17"
color-backtrace = "0.6.0"

luminol-audio = { version = "0.1.0", path = "../luminol-audio/" }
luminol-core = { version = "0.1.0", path = "../luminol-core/" }
luminol-config = { version = "0.1.0", path = "../luminol-config/" }
luminol-data = { version = "0.1.0", path = "../luminol-data/" }
luminol-filesystem = { version = "0.1.0", path = "../luminol-filesystem/" }
luminol-graphics = { version = "0.1.0", path = "../luminol-graphics/" }
luminol-ui = { version = "0.1.0", path = "../luminol-ui/" }
luminol-term = { version = "0.1.0", path = "../luminol-term/" }
# luminol-windows = { version = "0.1.0", path = "../luminol-windows/" }
# luminol-tabs = { version = "0.1.0", path = "../luminol-tabs/" }

poll-promise.workspace = true

camino.workspace = true

strum.workspace = true

[features]
steamworks = ["dep:steamworks", "crc"]

[target.'cfg(windows)'.build-dependencies]
winres = "0.1"

[package.metadata.winres]
OriginalFilename = "Luminol.exe"
ProductName = "Luminol"
