name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    env:
      RUST_BACKTRACE: 1
    strategy:
      matrix:
        build: [linux64, macos, win32, win64]
        include:
          - build: linux64
            os: ubuntu-latest
            channel: stable
            target: x86_64-unknown-linux-gnu
          #- build: linux32
          #  os: ubuntu-latest
          #  channel: stable
          #  target: i686-unknown-linux-gnu
          - build: macos
            os: macos-latest
            channel: stable
            target: x86_64-apple-darwin
          - build: win32
            os: windows-latest
            channel: stable
            target: i686-pc-windows-msvc
          - build: win64
            os: windows-latest
            channel: stable
            target: x86_64-pc-windows-msvc
    steps:
    - uses: actions/checkout@v2
    - run: |
        TOOLCHAIN=${{ matrix.channel }}-${{ matrix.target }}
        rustup toolchain install --no-self-update $TOOLCHAIN
        rustup default $TOOLCHAIN
      shell: bash
    - name: Rust version
      run: |
        set -ex
        rustc -Vv
        cargo -V
        rustup show
      shell: bash
    # Check build to fail fast
    - run: cargo check --target ${{ matrix.target }}
    - run: cargo build --target ${{ matrix.target }}
    - run: cargo test --target ${{ matrix.target }}
    # FIXME(#41): Some timeout/deadline tests make more sense to run in release mode.
    #- run: cargo test --release --target ${{ matrix.target }}
    - run: cargo build --all-targets --target ${{ matrix.target }}
    - run: cargo build --all-targets --no-default-features --target ${{ matrix.target }}
