on: [push]

name: Autobuild

jobs:
  build-ubuntu: 
    name: Build Ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Install libraries
        run: |
          sudo apt update
          sudo apt install libgtk-3-dev libatk1.0-dev libxcb-render0-dev libxcb-shape0-dev libxcb-xfixes0-dev libspeechd-dev libxkbcommon-dev libssl-dev libasound2-dev -y
      - uses: dtolnay/rust-toolchain@nightly
        with:
          toolchain: nightly-2023-04-21
      - name: Build luminol (Release)
        run: cargo build --features steamworks --release
      - name: Setup artifact
        run: |
          mkdir -p ${{ github.workspace }}/artifact
          cp ${{ github.workspace }}/target/release/luminol ${{ github.workspace }}/artifact
          cp ${{ github.workspace }}/steamworks/redistributable_bin/linux64/libsteam_api.so ${{ github.workspace }}/artifact
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: luminol-linux
          path: ${{ github.workspace }}/artifact/

  build-windows: 
    name: Build Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: dtolnay/rust-toolchain@nightly
        with:
          toolchain: nightly-2023-04-21
      - name: Build luminol (Release)
        run: cargo build --features steamworks --release
      - name: Setup artifact
        run: |
          mkdir -p ${{ github.workspace }}/artifact
          cp ${{ github.workspace }}/target/release/luminol.exe ${{ github.workspace }}/artifact
          cp ${{ github.workspace }}/steamworks/redistributable_bin/win64/steam_api64.dll ${{ github.workspace }}/artifact
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: luminol-windows
          path: ${{ github.workspace }}/artifact/

  build-mac: 
    name: Build MacOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: dtolnay/rust-toolchain@nightly
        with:
          toolchain: nightly-2023-04-21
      - name: Build luminol (Release)
        run: cargo build --features steamworks --release
      - name: Setup artifact
        run: |
          mkdir -p ${{ github.workspace }}/artifact
          cp ${{ github.workspace }}/target/release/luminol ${{ github.workspace }}/artifact
          cp ${{ github.workspace }}/steamworks/redistributable_bin/osx/libsteam_api.dylib ${{ github.workspace }}/artifact
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: luminol-mac
          path: ${{ github.workspace }}/artifact/

  deploy-steam:
    name: Deploy Steam
    runs-on: ubuntu-latest
    needs: [build-ubuntu, build-windows, build-mac]
    steps:
      - name: Extract branch name
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          path: ${{ github.workspace }}/artifacts
      - run: ls ${{ github.workspace }}/artifacts
      - name: Deploy to steam
        uses: game-ci/steam-deploy@v3
        with:
          username: ${{ secrets.STEAM_USERNAME }}          
          configVdf: ${{ secrets.STEAM_CONFIG_VDF}}          
          appId: 2501490
          buildDescription: beta test
          rootPath: artifacts # ??
          depot1Path: luminol-windows
          depot2Path: luminol-linux
          depot3Path: luminol-mac
          releaseBranch: beta # ${{ steps.extract_branch.outputs.branch }} todo: figure this out

