on: 
  push:
    paths-ignore:
      - '.github/**'
      - '.vscode/**'
      - '**.md'
  workflow_dispatch:

name: Autobuild

jobs:
  build-ubuntu: 
    name: Build Ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install libraries
        run: |
          sudo apt update
          sudo apt install libgtk-3-dev libatk1.0-dev libxcb-render0-dev libxcb-shape0-dev libxcb-xfixes0-dev libspeechd-dev libxkbcommon-dev libssl-dev libasound2-dev clang mold -y
      - uses: dtolnay/rust-toolchain@nightly
        with:
          toolchain: nightly-2024-05-19
      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
      - name: Build luminol (Release)
        run: cargo build --release 
      - name: Setup artifact
        run: |
          mkdir -p ${{ github.workspace }}/artifact
          cp ${{ github.workspace }}/target/release/luminol ${{ github.workspace }}/artifact
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: luminol-linux
          path: ${{ github.workspace }}/artifact/

  build-windows: 
    name: Build Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: dtolnay/rust-toolchain@nightly
        with:
          toolchain: nightly-2024-05-19
      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
      - name: Build luminol (Release)
        run: cargo build --release 
      - name: Setup artifact
        run: |
          mkdir -p ${{ github.workspace }}/artifact
          cp ${{ github.workspace }}/target/release/luminol.exe ${{ github.workspace }}/artifact
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: luminol-windows
          path: ${{ github.workspace }}/artifact/

  build-mac: 
    name: Build MacOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: dtolnay/rust-toolchain@nightly
        with:
          toolchain: nightly-2024-05-19
      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
      - name: Build luminol (Release)
        run: cargo build --release 
      - name: Setup artifact
        run: |
          mkdir -p ${{ github.workspace }}/artifact
          cp ${{ github.workspace }}/target/release/luminol ${{ github.workspace }}/artifact
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: luminol-mac
          path: ${{ github.workspace }}/artifact/

  build-trunk:
    name: Build Trunk
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install libraries
        run: |
          sudo apt update
          sudo apt install libgtk-3-dev libatk1.0-dev libxcb-render0-dev libxcb-shape0-dev libxcb-xfixes0-dev libspeechd-dev libxkbcommon-dev libssl-dev libasound2-dev clang mold -y
      - uses: dtolnay/rust-toolchain@nightly
        with:
          toolchain: nightly-2024-05-19
          targets: wasm32-unknown-unknown
          components: rust-src
      - name: Download and install Trunk binary
        run: wget -qO- https://github.com/trunk-rs/trunk/releases/download/v0.18.8/trunk-x86_64-unknown-linux-gnu.tar.gz | tar -xzf- -C ${{ runner.temp }}
      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
      - name: Build luminol (Release)
        run: ${{ runner.temp }}/trunk build --release
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: luminol-trunk
          path: ${{ github.workspace }}/dist/
