on: 
  push:
  workflow_dispatch:

name: Autobuild

jobs:
  build-ubuntu: 
    name: Build Ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Install libraries
        run: |
          sudo apt update
          sudo apt install libgtk-3-dev libatk1.0-dev libxcb-render0-dev libxcb-shape0-dev libxcb-xfixes0-dev libspeechd-dev libxkbcommon-dev libssl-dev libasound2-dev clang mold -y
      - uses: dtolnay/rust-toolchain@nightly
        with:
          toolchain: nightly-2023-09-12
      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
      - name: Build luminol (Release)
        run: cargo build --release --jobs 1
      - name: Setup artifact
        run: |
          mkdir -p ${{ github.workspace }}/artifact
          cp ${{ github.workspace }}/target/release/luminol ${{ github.workspace }}/artifact
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: luminol-linux
          path: ${{ github.workspace }}/artifact/

  build-windows: 
    name: Build Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: dtolnay/rust-toolchain@nightly
        with:
          toolchain: nightly-2023-09-12
      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
      - name: Build luminol (Release)
        run: cargo build --release --jobs 1
      - name: Setup artifact
        run: |
          mkdir -p ${{ github.workspace }}/artifact
          cp ${{ github.workspace }}/target/release/luminol.exe ${{ github.workspace }}/artifact
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: luminol-windows
          path: ${{ github.workspace }}/artifact/

  build-mac: 
    name: Build MacOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: dtolnay/rust-toolchain@nightly
        with:
          toolchain: nightly-2023-09-12
      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
      - name: Build luminol (Release)
        run: cargo build --release --jobs 1
      - name: Setup artifact
        run: |
          mkdir -p ${{ github.workspace }}/artifact
          cp ${{ github.workspace }}/target/release/luminol ${{ github.workspace }}/artifact\
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: luminol-mac
          path: ${{ github.workspace }}/artifact/